version: '3.8'
services:
  airflow:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - .:/app
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow scheduler & airflow webserver"
